package res.labosmtp.prankmail;

import java.util.LinkedList;
import java.util.Random;
import java.util.Scanner;

/**
 *
 * @author Ciani Antony, Hernandez Thomas
 * 
 * 
 * 
 */
public class Prank {
    
    
    private Mail prankMail;
    private Person sender;
    private Message message;
    
    
    Prank(Group group, LinkedList<Message> messages){
        
        sender = group.getSender();
        String senderAddr = sender.getEmailAddress();
        Random r = new Random();
        int messagePos = r.nextInt(messages.size());
        message = messages.get(messagePos);
        
        LinkedList<String> rcptsAdresses = group.getRecipientsEmails();
        prankMail = new Mail(senderAddr, message, rcptsAdresses);
        
    }

    /**
     * @return the Mail object generated by constructor
     */
    public Mail getPrankMail() {
        return prankMail;
    }
    

    
    
    
}
