package res.labosmtp.prankmail;

import java.util.LinkedList;
import java.util.Random;


/**
 *  This class is used to generate a prank email.
 *  It takes a group and select a random message from a list and build
 *  the resulting Mail object
 * 
 * @author Ciani Antony, Hernandez Thomas
 * 
 */
public class Prank {
    
    
    private Mail prankMail;
    private Person sender;
    private Message message;
    
    /**
     * Generates a Mail object from the addresses contained in the Group object and
     * a randomly picked message in the list
     * 
     * @param group
     * @param messages 
     */
    Prank(Group group, LinkedList<Message> messages){
        
        String senderAddr = group.getSenderEmail();
        Random r = new Random();
        int messagePos = r.nextInt(messages.size());
        message = messages.get(messagePos);
        
        LinkedList<String> rcptsAdresses = group.getRecipientsEmails();
        prankMail = new Mail(senderAddr, message, rcptsAdresses);
        
    }

    /**
     * @return the Mail object generated by constructor
     */
    public Mail getPrankMail() {
        return prankMail;
    }
    

    
    
    
}
